### ISSUE TITLE
User Story: Select option for which poll to vote in

### ISSUE THREAD

**Issue by mwarddev** [mwarddev/love-running#3]
In order to **vote for a specific subject** as a **site user**, I can **select which poll i wish to vote in**.

# Aceptance Criteria:
* Acceptance Criteria 1: An option to vote on a poll is clearly visible to the user.
* Acceptance Criteria 2: Options are offered to the user for which poll they wish to vote in.

# Tasks:
- [ ] Update HTML and CSS to add poll data to the site. This must include a button to add user votes.
- [ ] Update HTML and CSS subsection of the add user votes button press to allow users to vote on a specific poll (radio button).
- [ ] Update JavaScript add functionality to the vote button.
- [ ] Test functionality.
